services:
  db: 
    container_name: db
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - POSTGRES_DB=${POSTGRES_DB:-todolist}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-todolist}"] 
      interval: 5s 
      timeout: 5s 
      retries: 5

  migrate:
    container_name: migrate
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations/:/migrations
    command: [
      "-path", "/migrations/",
      "-database",
      "postgres://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-admin}@db:${POSTGRES_PORT:-5432}/${POSTGRES_DBNAME:-todolist}?sslmode=disable",
      "up"
    ]

