// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CreateTask(arg1:model.Task):Promise<void>;

export function Greet(arg1:model.Task):Promise<string>;
