// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CreateTask(arg1:model.Task):Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function GetFilteredAndSortedTasks(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<Array<model.Task>>;

export function GetTasks():Promise<Array<model.Task>>;

export function Greet(arg1:model.Task):Promise<string>;

export function UpdateTaskPriority(arg1:string,arg2:number):Promise<void>;

export function UpdateTaskStatus(arg1:string,arg2:string):Promise<void>;
